name: Marketing/Style Documentation
on: push

jobs:
  make_docs:
    runs-on: ubuntu-latest
    name: Build Docs
    steps:
    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'
        architecture: x64
    
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - run: sudo apt update

    - run: sudo apt install texlive-latex-recommended texlive-latex-extra texlive-pictures pandoc rename latexmk

    - name: Install docs requirements
      run: pip install -r docs/requirements.txt
    
    - name: Setup patches requirements
      run: pip install -r docs/uniforms/patches/requirements.txt
    
    - name: Generate patches
      run: cd docs && make patches

    - name: Build latexpdf
      run: cd docs && make latexpdf

    - run: mv docs/_build/latex/*.pdf docs/_build/latex/Tidal_Force_Uniform_and_Style_Guide.pdf

    - uses: actions/upload-artifact@v2
      with:
        name: Uniform_and_Style_Guide
        path: docs/_build/latex/Tidal_Force_Uniform_and_Style_Guide.pdf


  publish_docs:
    # Only run on tags
    if: github.event_name == 'push' && contains(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    name: Publish Docs
    needs: [make_docs]

    steps:
    - uses: actions/download-artifact@v2
      with:
        name: Uniform_and_Style_Guide

    - name: Upload Docs to release
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: '*.pdf'
        tag: ${{ github.ref }}
        overwrite: true
        body: "Tidal Force Robotics, Automated with github ci/cd."
        file_glob: true
