name: Make Docs
on:
  push:
    paths:
      - 'docs/**'
  release:

jobs:  
  make_style_guide:
    runs-on: ubuntu-latest
    name: Style Guide Builder
    steps:
    - name: Setup Python
      uses: actions/setup-python@v1
      with:
        python-version: 3.9
        architecture: x64
    
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - run: sudo apt update

    - run: sudo apt install texlive-latex-recommended texlive-latex-extra texlive-pictures pandoc rename latexmk

    - name: Install requirements
      run: pip install -r docs/requirements.txt

    - run: cd docs && make latexpdf

    - run: mv docs/_build/latex/tidalforceuniformandstyleguide.pdf docs/_build/latex/Tidal_Force_Uniform_and_Style_Guide.pdf

    - uses: actions/upload-artifact@v2
      with:
        name: Uniform_and_Style_Guide
        path: docs/_build/latex/Tidal_Force_Uniform_and_Style_Guide.pdf
